cask "keepassxc" unless test("d", "/Applications/KeePassXC.app")
cask "slack" unless test("d", "/Applications/Slack.app")
cask "phinze/cask/docker" unless test("x", "/usr/local/bin/docker")
cask "phinze/cask/gimp" unless test("d", "/Applications/GIMP.app")
cask "phinze/cask/kindle" unless test("d", "/Applications/Kindle.app")
cask "phinze/cask/skitch" unless test("d", "/Applications/Skitch.app")
cask "phinze/cask/night-owl" unless test("d", "/Applications/Night\ Owl.app")
cask "phinze/cask/appcleaner" unless test("d", "/Applications/AppCleaner.app")
cask "phinze/cask/dropbox" unless test("d", "/Applications/Dropbox.app")
cask "phinze/cask/iterm2" unless test("d", "/Applications/iTerm.app")
cask "phinze/cask/steermouse"
cask "phinze/cask/jasper" unless test("d", "/Applications/Jasper.app")
cask "phinze/cask/java" unless test("d", "/System/Library/Java")
cask "phinze/cask/hyperswitch" unless test("d", "/Applications/HyperSwitch.app")
cask "phinze/cask/google-chrome" unless test("d", "/Applications/Google\ Chrome.app")
cask "phinze/cask/google-japanese-ime" unless test("d", "/Applications/GoogleJapaneseInput.localized")
cask "phinze/cask/dash" unless test("d", "/Applications/Dash.app")
cask "phinze/cask/smcfancontrol" unless test("d", "/Applications/smcFanControl.app")
cask "phinze/cask/alfred" unless test("d", "/Applications/Alfred\ 4.app")
cask "phinze/cask/karabiner-elements" unless test("d", "/Applications/Karabiner-Elements.app")
cask "phinze/cask/marked" unless test("d", "/Applications/Marked\ 2.app")
cask "phinze/cask/vagrant" unless test("x", "/usr/local/bin/vagrant")
cask "phinze/cask/virtualbox" unless test("d", "/Applications/VirtualBox.app")
cask "phinze/cask/xquartz" unless test("x", "/opt/X11/bin/Xquartz")
cask "homebrew/cask-fonts/font-inconsolata"
cask "homebrew/cask-fonts/font-ricty-diminished"
tap "simeji/jid"
tap "laurent22/massren"
tap "caius/jo"
tap "phinze/cask"
tap "homebrew/brewdler"
tap "homebrew/core"
tap "homebrew/boneyard"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "monochromegane/pt"
tap "universal-ctags/universal-ctags"
brew "ack"
brew "gdbm"
brew "libyaml"
brew "openssl"
brew "ansible"
brew "gettext"
brew "pcre"
brew "glib"
brew "atk"
brew "autoconf"
brew "automake"
brew "xz"
brew "python"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bdw-gc"
brew "bison"
brew "boost", args: ["with-icu4c", "without-single"]
brew "c-ares"
brew "fontconfig"
brew "pixman"
brew "cairo"
brew "gmp"
brew "cloog"
brew "cmake", args: ["HEAD", "with-completion", "without-docs"]
brew "cmigemo"
brew "colordiff"
brew "coreutils"
brew "cpanminus"
brew "cscope"
brew "jansson"
brew "libev"
brew "libevent"
brew "libunistring"
brew "curl", args: ["with-libssh2", "with-nghttp2"]
brew "libusb"
brew "libusb-compat"
brew "dfu-programmer"
brew "dfu-util"
brew "direnv"
brew "docker-compose-completion"
brew "eigen"
brew "jpeg"
brew "wxmac"
brew "erlang"
brew "elixir"
brew "exa"
brew "exiftool"
brew "faac"
brew "fabric"
brew "lame"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "figlet"
brew "fish"
brew "fzf"
brew "isl"
brew "mpfr"
brew "gcc", args: ["with-jit", "with-nls"]
brew "gd"
brew "gdb"
brew "gdk-pixbuf"
brew "gem-completion"
brew "ghq"
brew "git"
brew "git-lfs"
brew "gobject-introspection"
brew "gsettings-desktop-schemas"
brew "icu4c"
brew "harfbuzz"
brew "hicolor-icon-theme"
brew "libepoxy"
brew "gtk+3"
brew "nspr"
brew "gjs"
brew "go"
brew "glide"
brew "gnu-sed", args: ["with-default-names"]
brew "libtasn1"
brew "nettle"
brew "libgpg-error"
brew "libgcrypt"
brew "gnupg"
brew "lua"
brew "gnuplot"
brew "gperftools"
brew "gradle"
brew "jasper"
brew "libtool"
brew "graphicsmagick"
brew "graphviz"
brew "groff"
brew "hub"
brew "ilmbase"
brew "imagemagick@6"
brew "imlib2"
brew "jo"
brew "mozjpeg"
brew "jpeg-archive"
brew "jpeg-turbo"
brew "oniguruma"
brew "jq"
brew "jsonpp"
brew "leiningen"
brew "memcached"
brew "libmemcached"
brew "libressl"
brew "libssh2"
brew "libvo-aacenc"
brew "libxml2"
brew "libxmlsec1"
brew "little-cms2"
brew "luajit"
brew "lv"
brew "lzlib"
brew "m4"
brew "makedepend"
brew "maven"
brew "mhash"
brew "mcrypt"
brew "md5deep"
brew "md5sha1sum"
brew "mecab"
brew "mercurial"
brew "mysql"
brew "nasm"
brew "ncurses"
brew "nkf"
brew "numpy"
brew "open-mpi"
brew "openexr"
brew "openjpeg"
brew "openssl@1.1"
brew "ossp-uuid"
brew "pandoc"
brew "poppler"
brew "pdfgrep"
brew "peco"
brew "phantomjs"
brew "postgresql"
brew "qt"
brew "pyqt"
brew "rails-completion"
brew "re2c"
brew "reattach-to-user-namespace", args: ["HEAD"]
brew "redis"
brew "s3cmd"
brew "sbt"
brew "scala"
brew "shared-mime-info"
brew "spdylay"
brew "sphinx-doc"
brew "sshfs"
brew "sslscan"
brew "texi2html"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "tig"
brew "tmux", args: ["with-utf8proc"]
brew "trash"
brew "tree"
brew "ttyrec"
brew "unixodbc"
brew "vagrant-completion"
brew "vim", args: ["with-luajit"]
brew "w3m"
brew "watchman"
brew "wget"
brew "yasm"
brew "z"
brew "zlib"
brew "zsh"
brew "zsh-completions"
brew "laurent22/massren/massren"
brew "simeji/jid/jid"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
