tap "caius/jo"
tap "homebrew/brewdler"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "laurent22/massren"
tap "monochromegane/pt"
tap "phinze/cask"
tap "simeji/jid"
tap "universal-ctags/universal-ctags"
brew "knqyf263/pet/pet"
brew "libyaml"
brew "openssl"
brew "xz"
brew "gettext"
brew "pcre"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "bdw-gc"
brew "bison"
brew "icu4c"
brew "boost"
brew "c-ares"
brew "fontconfig"
brew "pixman"
brew "cairo"
brew "clang-format"
brew "gmp"
brew "cloog"
brew "cmake"
brew "cmigemo"
brew "coreutils"
brew "cpanminus"
brew "cscope"
brew "curl"
brew "libusb"
brew "libusb-compat"
brew "dfu-programmer"
brew "dfu-util"
brew "direnv"
brew "docker-completion"
brew "docker-compose-completion"
brew "exiftool"
brew "faac"
brew "libevent"
brew "libtasn1"
brew "libunistring"
brew "lame"
brew "little-cms2"
brew "openjpeg"
brew "tesseract"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "figlet"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "gdb"
brew "gem-completion"
brew "ghq"
brew "git"
brew "git-lfs"
brew "go"
brew "glide"
brew "gnu-sed"
brew "libgpg-error"
brew "libgcrypt"
brew "gnupg"
brew "pkg-config"
brew "gperftools"
brew "gradle"
brew "jasper", link: false
brew "libtool"
brew "graphicsmagick"
brew "groff"
brew "gsettings-desktop-schemas"
brew "libepoxy"
brew "ncurses"
brew "htop"
brew "hub"
brew "ilmbase"
brew "shared-mime-info"
brew "openexr"
brew "imagemagick"
brew "imlib2"
brew "jansson"
brew "jo"
brew "mozjpeg"
brew "jpeg-archive"
brew "jpeg-turbo"
brew "oniguruma"
brew "jq"
brew "jsonpp"
brew "kubernetes-cli"
brew "libev"
brew "libressl"
brew "libssh2"
brew "libvo-aacenc"
brew "libxml2"
brew "libxmlsec1"
brew "luajit"
brew "lzlib"
brew "m4"
brew "makedepend"
brew "mhash"
brew "mcrypt"
brew "md5deep"
brew "md5sha1sum", link: false
brew "mecab"
brew "mercurial"
brew "nasm"
brew "nghttp2"
brew "nkf"
brew "openblas"
brew "numpy"
brew "open-mpi"
brew "openssl@1.1"
brew "ossp-uuid"
brew "pandoc"
brew "peco"
brew "qt"
brew "pyqt"
brew "re2c"
brew "reattach-to-user-namespace", args: ["HEAD"]
brew "redis", restart_service: true
brew "ripgrep"
brew "s3cmd"
brew "spdylay"
brew "sphinx-doc"
brew "sslscan"
brew "telnet"
brew "texi2html"
brew "the_platinum_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "ttyrec"
brew "unixodbc"
brew "vim"
brew "w3m"
brew "watchman"
brew "wget"
brew "wxmac"
brew "yasm"
brew "z"
brew "zlib"
brew "zsh"
brew "zsh-completions"
brew "laurent22/massren/massren"
brew "simeji/jid/jid"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "font-inconsolata"
cask "font-ricty-diminished"
cask "phinze/cask/keepassxc" unless test("d", "/Applications/KeePassXC.app")
cask "phinze/cask/docker" unless test("x", "/usr/local/bin/docker")
cask "phinze/cask/gimp" unless test("d", "/Applications/GIMP.app")
cask "phinze/cask/kindle" unless test("d", "/Applications/Kindle.app")
cask "phinze/cask/skitch" unless test("d", "/Applications/Skitch.app")
cask "phinze/cask/night-owl" unless test("d", "/Applications/Night\ Owl.app")
cask "phinze/cask/appcleaner" unless test("d", "/Applications/AppCleaner.app")
cask "phinze/cask/dropbox" unless test("d", "/Applications/Dropbox.app")
cask "phinze/cask/iterm2" unless test("d", "/Applications/iTerm.app")
cask "phinze/cask/steermouse"
cask "phinze/cask/jasper" unless test("d", "/Applications/Jasper.app")
cask "phinze/cask/java" unless test("d", "/System/Library/Java")
cask "phinze/cask/hyperswitch" unless test("d", "/Applications/HyperSwitch.app")
cask "phinze/cask/google-chrome" unless test("d", "/Applications/Google\ Chrome.app")
cask "phinze/cask/google-japanese-ime" unless test("d", "/Applications/GoogleJapaneseInput.localized")
cask "phinze/cask/dash" unless test("d", "/Applications/Dash.app")
cask "phinze/cask/alfred" unless test("d", "/Applications/Alfred\ 4.app")
cask "phinze/cask/karabiner-elements" unless test("d", "/Applications/Karabiner-Elements.app")
cask "phinze/cask/marked" unless test("d", "/Applications/Marked\ 2.app")
cask "phinze/cask/virtualbox" unless test("d", "/Applications/VirtualBox.app")
cask "phinze/cask/xquartz" unless test("x", "/opt/X11/bin/Xquartz")
